/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*; 

/**
 *
 * @author guilh
 */
public class JFrameAmigo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameAmigo
     */
    public JFrameAmigo(Aluno amigo) {
        this.amigo = amigo; 
        initComponents();
        this.setTitle(amigo.getNome() + "infos.");
        String out = "Nome: " + amigo.getNome(); 
        out += "\nRA: " + amigo.getRa();
        out += "\nCurso: " + amigo.getCurso(); 
        out += "\nMatriculas:\n"; 
        for (Turma turma:amigo.getTurmas()) {
            out += turma.getSigla();
            if (amigo.getTurmas().indexOf(turma) != amigo.getTurmas().size()-1)
                out += ", "; 
        }
        jTextPaneInfo.setText(out); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAmigo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInfo = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jTextPaneInfo.setEditable(false);
        jTextPaneInfo.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(jTextPaneInfo);

        javax.swing.GroupLayout jPanelAmigoLayout = new javax.swing.GroupLayout(jPanelAmigo);
        jPanelAmigo.setLayout(jPanelAmigoLayout);
        jPanelAmigoLayout.setHorizontalGroup(
            jPanelAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelAmigoLayout.setVerticalGroup(
            jPanelAmigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelAmigo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneInfo;
    // End of variables declaration//GEN-END:variables
    private Aluno amigo; 
}
