/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;

/**
 *
 * @author guilh
 */
public class JFrameTurmaProfessor extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrameTurmaProfessor
     */
    public JFrameTurmaProfessor(JFrameMain frameMain, Turma turma, Professor professor) {
        initComponents();
        this.frameMain = frameMain;
        this.turma = turma;
        this.professor = professor;
        setTitle(turma.getSigla()); 
        criaInfo(); 
        criaListaAlunos(); 
        criaListaPeds(); 
        criaListaPads(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInfo = new javax.swing.JTextPane();
        jButtonAdicionarAluno = new javax.swing.JButton();
        jButtonAdicionarPed = new javax.swing.JButton();
        jButtonRemoverAluno = new javax.swing.JButton();
        jButtonAdicionarPad = new javax.swing.JButton();
        jButtonRemoverPed = new javax.swing.JButton();
        jButtonRemoverPad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAlunos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPeds = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListPads = new javax.swing.JList<>();
        jButtonVoltar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGeral = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextPaneInfo.setEditable(false);
        jTextPaneInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações gerais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jScrollPane1.setViewportView(jTextPaneInfo);

        jButtonAdicionarAluno.setBackground(new java.awt.Color(201, 23, 48));
        jButtonAdicionarAluno.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonAdicionarAluno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarAluno.setText("Adicionar aluno");
        jButtonAdicionarAluno.setToolTipText("");

        jButtonAdicionarPed.setBackground(new java.awt.Color(201, 23, 48));
        jButtonAdicionarPed.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonAdicionarPed.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarPed.setText("Adicionar PED");
        jButtonAdicionarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPedActionPerformed(evt);
            }
        });

        jButtonRemoverAluno.setBackground(new java.awt.Color(201, 23, 48));
        jButtonRemoverAluno.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonRemoverAluno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemoverAluno.setText("Remover Aluno");

        jButtonAdicionarPad.setBackground(new java.awt.Color(201, 23, 48));
        jButtonAdicionarPad.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonAdicionarPad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarPad.setText("Adicionar PAD");

        jButtonRemoverPed.setBackground(new java.awt.Color(201, 23, 48));
        jButtonRemoverPed.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonRemoverPed.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemoverPed.setText("Remover PED");
        jButtonRemoverPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPedActionPerformed(evt);
            }
        });

        jButtonRemoverPad.setBackground(new java.awt.Color(201, 23, 48));
        jButtonRemoverPad.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonRemoverPad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemoverPad.setText("Remover PAD");

        jListAlunos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alunos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListAlunos.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListAlunos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há alunos nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAlunosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListAlunos);

        jListPeds.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEDs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListPeds.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListPeds.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há PEDs nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListPeds);

        jListPads.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PADs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListPads.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListPads.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há PADs nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListPads);

        jButtonVoltar.setBackground(new java.awt.Color(201, 23, 48));
        jButtonVoltar.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarPad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarAluno)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRemoverPad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverPed, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoverPed, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdicionarAluno)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonAdicionarPed)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonAdicionarPad)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoverPad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar)
                        .addContainerGap())))
        );

        jMenuGeral.setText("Geral");
        jMenuGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuGeralMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuGeral);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void criaInfo() {
        String out = "Nome: " + turma.getTurma();
        out += "\n Sigla: " + turma.getSigla();
        out += "\n Número de alunos: " + turma.getAlunos().size(); 
        out += "\n Número atividades: " + turma.getAtividades().size();
        jTextPaneInfo.setText(out); 
    }
    
    private void criaListaAlunos() {
        if(turma.getAlunos().size() != 0) {
            String[] listaAlunos = new String[turma.getAlunos().size()]; 
            int i = 0; 
            for(Aluno aluno:turma.getAlunos()) {
                listaAlunos[i] = aluno.getNome() + ", RA: " + aluno.getRa(); 
                i++; 
            }
            jListAlunos.setListData(listaAlunos);
        }
        else {
            String[] listaAlunos = {"Não há alunos nessa turma."}; 
            jListAlunos.setListData(listaAlunos); 
        } 
    }
    
    private void criaListaPeds() {
        if(turma.getPed().size() != 0) {
            String[] listaPed = new String[turma.getPed().size()]; 
            int i = 0; 
            for(Aluno ped:turma.getPed()) {
                listaPed[i] = ped.getNome() + ", RA: " + ped.getRa(); 
                i++; 
            }
            jListPeds.setListData(listaPed);
        }
        else {
            String[] listaPed = {"Não há PEDs nessa turma."}; 
            jListPeds.setListData(listaPed); 
        } 
    }
    
    private void criaListaPads() {
        if(turma.getPad().size() != 0) {
            String[] listaPad = new String[turma.getPad().size()]; 
            int i = 0; 
            for(Aluno pad:turma.getPad()) {
                listaPad[i] = pad.getNome() + ", RA: " + pad.getRa(); 
                i++; 
            }
            jListPads.setListData(listaPad);
        }
        else {
            String[] listaPad = {"Não há PADs nessa turma."}; 
            jListPads.setListData(listaPad); 
        } 
    }
    
    private void jButtonAdicionarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarPedActionPerformed

    private void jButtonRemoverPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoverPedActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        JPanelProf panel = new JPanelProf(professor, frameMain);
        frameMain.setContentPane(panel);
        frameMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jMenuGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuGeralMouseClicked
        // TODO add your handling code here:
        if(!getContentPane().equals(jPanel1)) {
            criaListaAlunos();
            criaListaPeds(); 
            criaListaPads();
            jPanel1.revalidate();
            jPanel1.repaint();
            setContentPane(jPanel1); 
        }
    }//GEN-LAST:event_jMenuGeralMouseClicked

    private void jListAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAlunosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && turma.getAlunos().size() != 0) {
            int index = jListAlunos.getSelectedIndex();
            Usuario aluno = turma.getAlunos().get(index);
            JFrameAlunoProf frameAlunoProf = new JFrameAlunoProf((Aluno)aluno);
            frameAlunoProf.setVisible(true);
        }
    }//GEN-LAST:event_jListAlunosMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarAluno;
    private javax.swing.JButton jButtonAdicionarPad;
    private javax.swing.JButton jButtonAdicionarPed;
    private javax.swing.JButton jButtonRemoverAluno;
    private javax.swing.JButton jButtonRemoverPad;
    private javax.swing.JButton jButtonRemoverPed;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JList<String> jListAlunos;
    private javax.swing.JList<String> jListPads;
    private javax.swing.JList<String> jListPeds;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGeral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPaneInfo;
    // End of variables declaration//GEN-END:variables
    private JFrameMain frameMain;
    private Turma turma;
    private Professor professor; 
}
