/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;

/**
 *
 * @author guilh
 */
public class JFrameTurmaProfessor extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrameTurmaProfessor
     */
    public JFrameTurmaProfessor(JFrameMain frameMain, Turma turma, Professor professor) {
        initComponents();
        this.frameMain = frameMain;
        this.turma = turma;
        this.professor = professor;
        setTitle(turma.getSigla()); 
        criaInfo(); 
        criaListaAlunos(); 
        criaListaPeds(); 
        criaListaPads(); 
        criaListaAtv();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInfo = new javax.swing.JTextPane();
        jButtonAdicionarAluno = new javax.swing.JButton();
        jButtonAdicionarPed = new javax.swing.JButton();
        jButtonRemoverAluno = new javax.swing.JButton();
        jButtonAdicionarPad = new javax.swing.JButton();
        jButtonRemoverPed = new javax.swing.JButton();
        jButtonRemoverPad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAlunos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPeds = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListPads = new javax.swing.JList<>();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGeral = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextPaneInfo.setEditable(false);
        jTextPaneInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações gerais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jScrollPane1.setViewportView(jTextPaneInfo);

        jButtonAdicionarAluno.setBackground(new java.awt.Color(201, 23, 48));
        jButtonAdicionarAluno.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonAdicionarAluno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarAluno.setText("Adicionar aluno");
        jButtonAdicionarAluno.setToolTipText("");
        jButtonAdicionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAlunoActionPerformed(evt);
            }
        });

        jButtonAdicionarPed.setBackground(new java.awt.Color(201, 23, 48));
        jButtonAdicionarPed.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonAdicionarPed.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarPed.setText("Adicionar PED");
        jButtonAdicionarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPedActionPerformed(evt);
            }
        });

        jButtonRemoverAluno.setBackground(new java.awt.Color(201, 23, 48));
        jButtonRemoverAluno.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonRemoverAluno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemoverAluno.setText("Remover Aluno");
        jButtonRemoverAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverAlunoActionPerformed(evt);
            }
        });

        jButtonAdicionarPad.setBackground(new java.awt.Color(201, 23, 48));
        jButtonAdicionarPad.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonAdicionarPad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarPad.setText("Adicionar PAD");
        jButtonAdicionarPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPadActionPerformed(evt);
            }
        });

        jButtonRemoverPed.setBackground(new java.awt.Color(201, 23, 48));
        jButtonRemoverPed.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonRemoverPed.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemoverPed.setText("Remover PED");
        jButtonRemoverPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPedActionPerformed(evt);
            }
        });

        jButtonRemoverPad.setBackground(new java.awt.Color(201, 23, 48));
        jButtonRemoverPad.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonRemoverPad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemoverPad.setText("Remover PAD");
        jButtonRemoverPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPadActionPerformed(evt);
            }
        });

        jListAlunos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alunos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListAlunos.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListAlunos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há alunos nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAlunosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListAlunos);

        jListPeds.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEDs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListPeds.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListPeds.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há PEDs nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPeds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPedsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListPeds);

        jListPads.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PADs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListPads.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListPads.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há PADs nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPads.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPadsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListPads);

        jButtonVoltar.setBackground(new java.awt.Color(201, 23, 48));
        jButtonVoltar.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nenhuma atividade" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList1);

        jButton1.setText("Criar Atividade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdicionarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicionarAluno)
                            .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicionarPad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRemoverPad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoverPed, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButtonAdicionarPad)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoverPed, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButtonAdicionarAluno)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButtonAdicionarPed)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonRemoverPad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jMenuGeral.setText("Geral");
        jMenuGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuGeralMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuGeral);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void criaInfo() {
        String out = "Nome: " + turma.getTurma();
        out += "\n Sigla: " + turma.getSigla();
        out += "\n Número de alunos: " + turma.getAlunos().size(); 
        out += "\n Número atividades: " + turma.getAtividades().size();
        jTextPaneInfo.setText(out); 
    }
    
    public void criaListaAlunos() {
        if(turma.getAlunos().size() != 0) {
            String[] listaAlunos = new String[turma.getAlunos().size()]; 
            int i = 0; 
            for(Aluno aluno:turma.getAlunos()) {
                listaAlunos[i] = aluno.getNome() + ", RA: " + aluno.getRa(); 
                i++; 
            }
            jListAlunos.setListData(listaAlunos);
        }
        else {
            String[] listaAlunos = {"Não há alunos nessa turma."}; 
            jListAlunos.setListData(listaAlunos); 
        } 
    }
    
    public void criaListaAtv() {
        if (turma.getAtividades().size() != 0) {
            String[] listaAtv = new String[turma.getAtividades().size()];
            int i = 0; 
            for(Atividade atv :turma.getAtividades()) {
                listaAtv[i] = atv.getAgendaAluno().getTitulo(); 
                i++; 
            }
            jList1.setListData(listaAtv);
        }
    }
    
    public void criaListaPeds() {
        if(turma.getPed().size() != 0) {
            String[] listaPed = new String[turma.getPed().size()]; 
            int i = 0; 
            for(Aluno ped:turma.getPed()) {
                listaPed[i] = ped.getNome() + ", RA: " + ped.getRa(); 
                i++; 
            }
            jListPeds.setListData(listaPed);
        }
        else {
            String[] listaPed = {"Não há PEDs nessa turma."}; 
            jListPeds.setListData(listaPed); 
        } 
    }
    
    public void criaListaPads() {
        if(turma.getPad().size() != 0) {
            String[] listaPad = new String[turma.getPad().size()]; 
            int i = 0; 
            for(Aluno pad:turma.getPad()) {
                listaPad[i] = pad.getNome() + ", RA: " + pad.getRa(); 
                i++; 
            }
            jListPads.setListData(listaPad);
        }
        else {
            String[] listaPad = {"Não há PADs nessa turma."}; 
            jListPads.setListData(listaPad); 
        } 
    }
    
    private void jButtonAdicionarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPedActionPerformed
        // TODO add your handling code here:
        JFrameAdicionar frameAdicionar = new JFrameAdicionar(this, turma, professor, "PED");
        frameAdicionar.setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarPedActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        JPanelProf panel = new JPanelProf(professor, frameMain);
        frameMain.setContentPane(panel);
        frameMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jMenuGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuGeralMouseClicked
        // TODO add your handling code here:
        if(!getContentPane().equals(jPanel1)) {
            criaListaAlunos();
            criaListaPeds(); 
            criaListaPads();
            jPanel1.revalidate();
            jPanel1.repaint();
            setContentPane(jPanel1); 
        }
    }//GEN-LAST:event_jMenuGeralMouseClicked

    private void jListAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAlunosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && turma.getAlunos().size() != 0) {
            int index = jListAlunos.getSelectedIndex();
            Usuario aluno = turma.getAlunos().get(index);
            JFrameAlunoProf frameAlunoProf = new JFrameAlunoProf((Aluno)aluno);
            frameAlunoProf.setVisible(true);
        }
    }//GEN-LAST:event_jListAlunosMouseClicked

    private void jButtonRemoverAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverAlunoActionPerformed
        // TODO add your handling code here:
        if (turma.getAlunos().size() != 0) {
            int index = jListAlunos.getSelectedIndex(); 
            turma.removeAluno(professor, turma.getAlunos().get(index));
            criaListaAlunos(); 
            jPanel1.revalidate();
            jPanel1.repaint(); 
        }
    }//GEN-LAST:event_jButtonRemoverAlunoActionPerformed

    private void jButtonRemoverPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPedActionPerformed
        // TODO add your handling code here:
        if (turma.getPed().size() != 0) {
            int index = jListPeds.getSelectedIndex(); 
            turma.removePed(professor, turma.getPed().get(index));
            criaListaPeds(); 
            jPanel1.revalidate();
            jPanel1.repaint(); 
        }
    }//GEN-LAST:event_jButtonRemoverPedActionPerformed

    private void jButtonRemoverPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPadActionPerformed
        // TODO add your handling code here:
        if (turma.getPad().size() != 0) {
            int index = jListPads.getSelectedIndex(); 
            turma.removePad(professor, turma.getPad().get(index));
            criaListaPads(); 
            jPanel1.revalidate();
            jPanel1.repaint(); 
        }
    }//GEN-LAST:event_jButtonRemoverPadActionPerformed

    private void jButtonAdicionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAlunoActionPerformed
        // TODO add your handling code here:
        JFrameAdicionar frameAdicionar = new JFrameAdicionar(this, turma, professor, "ALUNO");
        frameAdicionar.setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarAlunoActionPerformed

    private void jButtonAdicionarPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPadActionPerformed
        // TODO add your handling code here:
        JFrameAdicionar frameAdicionar = new JFrameAdicionar(this, turma, professor, "PAD");
        frameAdicionar.setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarPadActionPerformed

    private void jListPedsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPedsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && turma.getPed().size() != 0) {
            int index = jListPeds.getSelectedIndex();
            Usuario ped = turma.getPed().get(index);
            JFrameAlunoProf frameAlunoProf = new JFrameAlunoProf((Aluno)ped);
            frameAlunoProf.setVisible(true);
        }
    }//GEN-LAST:event_jListPedsMouseClicked

    private void jListPadsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPadsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && turma.getPad().size() != 0) {
            int index = jListPads.getSelectedIndex();
            Usuario pad = turma.getPad().get(index);
            JFrameAlunoProf frameAlunoProf = new JFrameAlunoProf((Aluno)pad);
            frameAlunoProf.setVisible(true);
        }
    }//GEN-LAST:event_jListPadsMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            int index = jList1.getSelectedIndex();
            Atividade atividade = turma.getAtividades().get(index);
            JFrameAtividade atvPanel = new JFrameAtividade(atividade);
            atvPanel.setVisible(true);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrameNovaAtividade novatv = new JFrameNovaAtividade(turma, this, professor);
        novatv.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public javax.swing.JPanel getJPanel() {
        return jPanel1; 
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdicionarAluno;
    private javax.swing.JButton jButtonAdicionarPad;
    private javax.swing.JButton jButtonAdicionarPed;
    private javax.swing.JButton jButtonRemoverAluno;
    private javax.swing.JButton jButtonRemoverPad;
    private javax.swing.JButton jButtonRemoverPed;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListAlunos;
    private javax.swing.JList<String> jListPads;
    private javax.swing.JList<String> jListPeds;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGeral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPaneInfo;
    // End of variables declaration//GEN-END:variables
    private JFrameMain frameMain;
    private Turma turma;
    private Professor professor; 
}
