/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*; 

/**
 *
 * @author guilh
 */
public class JFrameSolicitacao extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSolicitacao
     */
    public JFrameSolicitacao(JPanelAluno panel, JFrameMain frameMain, Solicitacao solicitacao, Aluno receptor) {
        initComponents();
        this.panel = panel;
        this.frameMain = frameMain; 
        this.receptor = receptor; 
        this.solicitacao = solicitacao; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jButtonSim = new javax.swing.JButton();
        jButtonNao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Aceitar solicitação?");

        jButtonSim.setBackground(new java.awt.Color(201, 23, 48));
        jButtonSim.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jButtonSim.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSim.setText("Sim");
        jButtonSim.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSim.setMaximumSize(new java.awt.Dimension(51, 26));
        jButtonSim.setMinimumSize(new java.awt.Dimension(51, 26));
        jButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimActionPerformed(evt);
            }
        });

        jButtonNao.setBackground(new java.awt.Color(201, 23, 48));
        jButtonNao.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jButtonNao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNao.setText("Não");
        jButtonNao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jButtonSim, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonNao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNao, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButtonSim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimActionPerformed
        // TODO add your handling code here:
        receptor.aceitarSolicitacao(solicitacao, true);
        this.setVisible(false); 
        JPanelAluno panel = new JPanelAluno(receptor, frameMain);
        frameMain.setContentPane(panel); 
        panel.revalidate();
        panel.repaint(); 
    }//GEN-LAST:event_jButtonSimActionPerformed

    private void jButtonNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNaoActionPerformed
        // TODO add your handling code here:
        receptor.aceitarSolicitacao(solicitacao, false); 
        this.setVisible(false);  
        JPanelAluno panel = new JPanelAluno(receptor, frameMain); 
        frameMain.setContentPane(panel); 
        panel.revalidate();
        panel.repaint(); 
    }//GEN-LAST:event_jButtonNaoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNao;
    private javax.swing.JButton jButtonSim;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private Solicitacao solicitacao; 
    private Aluno receptor; 
    private JFrameMain frameMain; 
    private JPanelAluno panel;
}
