/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*; 

/**
 *
 * @author guilh
 */
public class JFrameDuvida extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDuvida
     */
    public JFrameDuvida(Duvidas duvida, Aluno aluno) {
        initComponents();
        this.duvida = duvida;
        this.aluno = aluno; 
        setTitle("Duvida " + duvida.getIndagador().getNome());
        criaIndagacao();
        criaRespostas(); 
        if (!duvida.getIndagador().equals(aluno)) {
            jButtonResolver.setVisible(false);
        }
        if (duvida.isResolvido()) {
            jTextFieldResponder.setVisible(false);
            jButtonResponder.setVisible(false); 
        }
    }
    
    public void criaIndagacao() {
        jTextPaneIndagacao.setText(duvida.getIndagacao());
    }
    
    public void criaRespostas() {
        String out = ""; 
        for(Mensagem mensagem:duvida.getComentarios()) {
            if (mensagem.getSujeito() == aluno)
                out += "Você: ";
            else
                out += mensagem.getSujeito().getNome() + ": ";
            out += mensagem.getTexto();
            if (duvida.getComentarios().indexOf(mensagem) != duvida.getComentarios().size()-1) {
                out += "\n";
            }
        }
        jTextPaneRespostas.setText(out); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneIndagacao = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneRespostas = new javax.swing.JTextPane();
        jButtonResponder = new javax.swing.JButton();
        jTextFieldResponder = new javax.swing.JTextField();
        jButtonResolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextPaneIndagacao.setEditable(false);
        jTextPaneIndagacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indagação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jTextPaneIndagacao.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(jTextPaneIndagacao);

        jTextPaneRespostas.setEditable(false);
        jTextPaneRespostas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respostas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jTextPaneRespostas.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jScrollPane2.setViewportView(jTextPaneRespostas);

        jButtonResponder.setBackground(new java.awt.Color(201, 23, 48));
        jButtonResponder.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonResponder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResponder.setText("Responder");
        jButtonResponder.setBorder(null);
        jButtonResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResponderActionPerformed(evt);
            }
        });

        jTextFieldResponder.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N

        jButtonResolver.setBackground(new java.awt.Color(201, 23, 48));
        jButtonResolver.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonResolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResolver.setText("Resolver");
        jButtonResolver.setBorder(null);
        jButtonResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonResponder, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jButtonResolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonResponder, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addComponent(jTextFieldResponder))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResponderActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldResponder.getText().equals("")) {
            String out = jTextFieldResponder.getText(); 
            jTextFieldResponder.setText("");
            duvida.replicar(aluno, out);
            criaRespostas(); 
            jPanel1.revalidate();
            jPanel1.repaint();
        }
    }//GEN-LAST:event_jButtonResponderActionPerformed

    private void jButtonResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverActionPerformed
        // TODO add your handling code here:
        duvida.resolver();
    }//GEN-LAST:event_jButtonResolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResolver;
    private javax.swing.JButton jButtonResponder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldResponder;
    private javax.swing.JTextPane jTextPaneIndagacao;
    private javax.swing.JTextPane jTextPaneRespostas;
    // End of variables declaration//GEN-END:variables
    Aluno aluno;
    Duvidas duvida; 
}
