/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;

/**
 *
 * @author guilh
 */
public class JPanelTurma extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTurma
     */
    public JPanelTurma(JFrameMain frameMain, Turma turma, Aluno aluno) {
        initComponents();
        this.frameMain = frameMain; 
        this.turma = turma;
        this.aluno = aluno;
        String out = "Nome: " + turma.getTurma();
        out += "\nSigla: " + turma.getSigla();
        out += "\nProfessor: " + turma.getProfessor().getNome(); 
        jTextPaneInfo.setText(out); 
        criaListaAlunos();
        criaListaDuvidas(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInfo = new javax.swing.JTextArea();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAlunos = new javax.swing.JList<>();
        jButtonEmenta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDuvidas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldDuvida = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextPaneInfo.setEditable(false);
        jTextPaneInfo.setColumns(20);
        jTextPaneInfo.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jTextPaneInfo.setRows(5);
        jTextPaneInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações gerais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jScrollPane1.setViewportView(jTextPaneInfo);

        jButtonVoltar.setBackground(new java.awt.Color(201, 23, 48));
        jButtonVoltar.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(null);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jListAlunos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alunos na turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListAlunos.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListAlunos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há pessoas nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAlunosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListAlunos);

        jButtonEmenta.setBackground(new java.awt.Color(201, 23, 48));
        jButtonEmenta.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButtonEmenta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmenta.setText("Ver ementa");
        jButtonEmenta.setBorder(null);
        jButtonEmenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmentaActionPerformed(evt);
            }
        });

        jListDuvidas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dúvidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListDuvidas.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListDuvidas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há dúvidas nessa turma." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListDuvidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDuvidasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListDuvidas);

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monitorias abertas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jList1.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Não há monitorias abertas no momento." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jButton1.setBackground(new java.awt.Color(201, 23, 48));
        jButton1.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButton1.setText("Abrir");

        jButton2.setBackground(new java.awt.Color(201, 23, 48));
        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Criar Duvida");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldDuvida.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jButtonEmenta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDuvida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEmenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDuvida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void criaListaAlunos() {
        if(turma.getAlunos().size() != 0) {
            String[] listaAlunos = new String[turma.getAlunos().size()]; 
            int i = 0; 
            for(Aluno aluno:turma.getAlunos()) {
                listaAlunos[i] = aluno.getNome() + ", RA: " + aluno.getRa(); 
                i++; 
            }
            jListAlunos.setListData(listaAlunos);
        }
    }
    
    private void criaListaDuvidas() {
        if(turma.getDuvidas().size() != 0) {
            String[] listaDuvidas = new String[turma.getDuvidas().size()];
            int i = 0; 
            for(Duvidas duvida:turma.getDuvidas()) {
                listaDuvidas[i] = "Duvida de " + duvida.getIndagador().getNome(); 
                i++; 
            }
            jListDuvidas.setListData(listaDuvidas); 
        }
    }
    
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        JPanelAluno panel = new JPanelAluno(aluno, frameMain);
        frameMain.setContentPane(panel);
        panel.revalidate();
        panel.repaint(); 
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jListAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAlunosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && aluno.getAmigos().size() != 0) {
            int index = jListAlunos.getSelectedIndex(); 
            Usuario amigo = turma.getAlunos().get(index); 
            JFrameAmigo frameAmigo = new JFrameAmigo(aluno, (Aluno)amigo); 
            frameAmigo.setVisible(true); 
        }
    }//GEN-LAST:event_jListAlunosMouseClicked

    private void jButtonEmentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmentaActionPerformed
        // TODO add your handling code here:
        JFrameEmenta frameEmenta = new JFrameEmenta(turma); 
        frameEmenta.setVisible(true); 
    }//GEN-LAST:event_jButtonEmentaActionPerformed

    private void jListDuvidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDuvidasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && turma.getDuvidas().size() != 0) {
            int index = jListDuvidas.getSelectedIndex();
            Duvidas duvida = turma.getDuvidas().get(index);
            JFrameDuvida frameDuvida = new JFrameDuvida(duvida, aluno);
            frameDuvida.setVisible(true);
        }
    }//GEN-LAST:event_jListDuvidasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String out = jTextFieldDuvida.getText();
        turma.criarDuvida(aluno, out); 
        criaListaDuvidas(); 
        this.revalidate();
        this.repaint(); 
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEmenta;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListAlunos;
    private javax.swing.JList<String> jListDuvidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldDuvida;
    private javax.swing.JTextArea jTextPaneInfo;
    // End of variables declaration//GEN-END:variables
    private Turma turma;
    private Aluno aluno;
    private JFrameMain frameMain; 
}
