/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*; 
import java.util.HashMap;
import java.util.Set;
import java.util.ArrayList;
import java.util.Collections; 
/**
 *
 * @author guilh
 */
public class JPanelAluno extends javax.swing.JPanel {

    /**
     * Creates new form JPanelAluno
     */
    public JPanelAluno(Aluno aluno, JFrameMain frame) {
        initComponents();
        this.aluno = aluno; 
        this.frameMain = frame; 
        this.perfil = new JPanelPerfil(aluno.visualizarInfo(aluno));
        this.grade = new JPanelGrade(aluno);
        this.agenda = new JPanelAgenda(aluno.getAgenda().toString());

        
        // List de amigos
        criaListaAmigos();
        
        // List de Turmas
        criaRelacionadoTurma(); 
        
        // List de solicitacoes
        criaSolicitacoes(); 
        
        // List de feed
        criaFeed(); 
        
        panelBusca.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelColuna = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonBusca = new javax.swing.JButton();
        jButtonNotificacoes = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jButtonGrade = new javax.swing.JButton();
        jButtonPerfil = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAmigos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAmigos = new javax.swing.JList<>();
        jPanelTurmas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListTurmas = new javax.swing.JList<>();
        jPanelSolicitacoes = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListSolicitacoes = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListFeed = new javax.swing.JList<>();
        panelBusca = new javax.swing.JPanel();
        jTextFieldBusca = new javax.swing.JTextField();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(700, 521));

        jSplitPane1.setBackground(java.awt.Color.white);

        panelColuna.setBackground(new java.awt.Color(201, 23, 48));
        panelColuna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonExit.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButtonExit.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setas-flechas (2) (1).png"))); // NOI18N
        jButtonExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonExit.setContentAreaFilled(false);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/png-transparent-preview (1).png"))); // NOI18N
        jButtonBusca.setToolTipText("");
        jButtonBusca.setAutoscrolls(true);
        jButtonBusca.setBorder(null);
        jButtonBusca.setContentAreaFilled(false);
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });

        jButtonNotificacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sino__1_-removebg-preview (2).png"))); // NOI18N
        jButtonNotificacoes.setBorder(null);
        jButtonNotificacoes.setContentAreaFilled(false);
        jButtonNotificacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotificacoesActionPerformed(evt);
            }
        });

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendario-removebg-preview (1) (1).png"))); // NOI18N
        jButtonAgenda.setBorder(null);
        jButtonAgenda.setContentAreaFilled(false);
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });

        jButtonGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sketchbook-removebg-preview (1).png"))); // NOI18N
        jButtonGrade.setBorder(null);
        jButtonGrade.setContentAreaFilled(false);
        jButtonGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGradeActionPerformed(evt);
            }
        });

        jButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/do-utilizador-removebg-preview (2).png"))); // NOI18N
        jButtonPerfil.setBorder(null);
        jButtonPerfil.setContentAreaFilled(false);
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botao-home-para-interface-removebg-preview (1).png"))); // NOI18N
        jButtonHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelColunaLayout = new javax.swing.GroupLayout(panelColuna);
        panelColuna.setLayout(panelColunaLayout);
        panelColunaLayout.setHorizontalGroup(
            panelColunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelColunaLayout.setVerticalGroup(
            panelColunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonBusca)
                .addGap(28, 28, 28)
                .addComponent(jButtonAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(panelColuna);

        panelHome.setBackground(java.awt.Color.white);
        panelHome.setOpaque(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N

        jPanelAmigos.setBackground(new java.awt.Color(255, 255, 255));

        jListAmigos.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListAmigos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Você não tem amigos para exibir." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAmigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListAmigos);

        javax.swing.GroupLayout jPanelAmigosLayout = new javax.swing.GroupLayout(jPanelAmigos);
        jPanelAmigos.setLayout(jPanelAmigosLayout);
        jPanelAmigosLayout.setHorizontalGroup(
            jPanelAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
            .addGroup(jPanelAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
        );
        jPanelAmigosLayout.setVerticalGroup(
            jPanelAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanelAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Amigos", jPanelAmigos);

        jPanelTurmas.setBackground(new java.awt.Color(255, 255, 255));

        jListTurmas.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListTurmas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Você não tem turmas para exibir." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTurmasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListTurmas);

        javax.swing.GroupLayout jPanelTurmasLayout = new javax.swing.GroupLayout(jPanelTurmas);
        jPanelTurmas.setLayout(jPanelTurmasLayout);
        jPanelTurmasLayout.setHorizontalGroup(
            jPanelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanelTurmasLayout.setVerticalGroup(
            jPanelTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Turmas", jPanelTurmas);

        jPanelSolicitacoes.setBackground(new java.awt.Color(255, 255, 255));

        jListSolicitacoes.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListSolicitacoes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Você não tem solicitações pendentes." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSolicitacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListSolicitacoesMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(jListSolicitacoes);

        javax.swing.GroupLayout jPanelSolicitacoesLayout = new javax.swing.GroupLayout(jPanelSolicitacoes);
        jPanelSolicitacoes.setLayout(jPanelSolicitacoesLayout);
        jPanelSolicitacoesLayout.setHorizontalGroup(
            jPanelSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanelSolicitacoesLayout.setVerticalGroup(
            jPanelSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Solicitações", jPanelSolicitacoes);

        jListFeed.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Feed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 11))); // NOI18N
        jListFeed.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jListFeed.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Você não tem nada novo." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListFeed);

        panelBusca.setBackground(java.awt.Color.white);
        panelBusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextFieldBusca.setText("Busca...");
        jTextFieldBusca.setActionCommand("<Not Set>");
        jTextFieldBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBuscaLayout = new javax.swing.GroupLayout(panelBusca);
        panelBusca.setLayout(panelBuscaLayout);
        panelBuscaLayout.setHorizontalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBuscaLayout.setVerticalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addComponent(panelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                        .addGap(0, 66, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(panelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Amigos");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        jSplitPane1.setRightComponent(panelHome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 109, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    private void criaListaAmigos() {
        if (aluno.getAmigos().size() != 0) {
            String[] listaAmigos = new String[aluno.getAmigos().size()];
            int i = 0; 
            for(Usuario amigo:aluno.getAmigos()) {
                listaAmigos[i] = amigo.getNome(); 
                i++; 
            }
            jListAmigos.setListData(listaAmigos);
        }
    }
    
    private void criaRelacionadoTurma() {
         if (aluno.getTurmas().size() != 0) {
            String[] listaTurmas = new String[aluno.getTurmas().size()]; 
            int aux = 0;
            for(Turma turma:aluno.getTurmas()) {
                listaTurmas[aux] = turma.getSigla(); 
                aux++; 
            }
            jListTurmas.setListData(listaTurmas);
         }      
    }

    private void criaSolicitacoes() {
        if (aluno.getSolicitacoes().size() != 0) {
            String[] listaSolicitacoes = new String[aluno.getSolicitacoes().size()];
            int i = 0;
            for (Solicitacao solicitacao:aluno.getSolicitacoes()) {
                listaSolicitacoes[i] = solicitacao.toString();
                i++; 
            }
            jListSolicitacoes.setListData(listaSolicitacoes); 
        }
    }
    
    private void criaFeed() {
        if (aluno.getFeedAluno().size() != 0) {
            String[] listaFeed = new String[aluno.getFeedAluno().size()];
            int i = 0; 
            for(Feed feed:aluno.getFeedAluno()) {
                listaFeed[i] = feed.exibirFeed(); 
                i++; 
            }
            jListFeed.setListData(listaFeed); 
        }
    }
    
    private void jListAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAmigosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && aluno.getAmigos().size() != 0) {
            int index = jListAmigos.getSelectedIndex(); 
            Usuario amigo = aluno.getAmigos().get(index); 
            JFrameAmigo frameAmigo = new JFrameAmigo(aluno, (Aluno)amigo); 
            frameAmigo.setVisible(true); 
        }
    }//GEN-LAST:event_jListAmigosMouseClicked

    private void jListTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTurmasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && aluno.getTurmas().size() != 0) {
            int index = jListTurmas.getSelectedIndex();
            Turma turma = aluno.getTurmas().get(index); 
            JFrameTurma frameTurma = new JFrameTurma(frameMain, turma, aluno); 
            frameTurma.setVisible(true);
            frameMain.setVisible(false);
        }
    }//GEN-LAST:event_jListTurmasMouseClicked

    private void jListSolicitacoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSolicitacoesMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && aluno.getSolicitacoes().size() != 0) { 
            int index = jListSolicitacoes.getSelectedIndex(); 
            Solicitacao solicitacao = aluno.getSolicitacoes().get(index); 
            JFrameSolicitacao frameSolicitacao = new JFrameSolicitacao(this, frameMain, solicitacao, aluno);
            frameSolicitacao.setVisible(true); 
        }
    }//GEN-LAST:event_jListSolicitacoesMousePressed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        JFrameExit exit = new JFrameExit(frameMain);
        exit.setVisible(true);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        // TODO add your handling code here:
        if(jSplitPane1.getRightComponent() != panelHome){
            jSplitPane1.setRightComponent(panelHome);
        }
        
        if(!panelBusca.isVisible()){
           panelBusca.setVisible(true);
        }
        else if(jTextFieldBusca.getText().equals("Busca...") || jTextFieldBusca.getText().equals("")
                || jTextFieldBusca.getText().equals("Usuário não encontrado")){
            panelBusca.setVisible(false);
        }
        else{
            String out = jTextFieldBusca.getText();                

            boolean verif = false;
            for(Usuario u : Usuario.getUsuarios()){
                if(u.getNome().equals(out)){
                    JFrameAmigo busca = new JFrameAmigo(aluno, (Aluno) u);
                    busca.setVisible(true);
                    jTextFieldBusca.setText("Busca...");
                    jTextFieldBusca.setVisible(false);
                    verif = true;
                }
            }
            
            if(!verif){
                jTextFieldBusca.setForeground(java.awt.Color.red);
                jTextFieldBusca.setText("Usuário não encontrado");
            }
        }
    }//GEN-LAST:event_jButtonBuscaActionPerformed

    private void jTextFieldBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscaMouseClicked
        // TODO add your handling code here:
        jTextFieldBusca.setText("");
        jTextFieldBusca.setForeground(new java.awt.Color(93, 93, 93));
    }//GEN-LAST:event_jTextFieldBuscaMouseClicked

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        if(jSplitPane1.getRightComponent() != panelHome){
            jSplitPane1.setRightComponent(panelHome);
        }
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonNotificacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotificacoesActionPerformed
        // TODO add your handling code here:
        JFrameNotificacoes notificacao = new JFrameNotificacoes(aluno.exibirNotificacoes(aluno));
        notificacao.setVisible(true);
    }//GEN-LAST:event_jButtonNotificacoesActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        // TODO add your handling code here:
        if(jSplitPane1.getRightComponent() != perfil){
            jSplitPane1.setRightComponent(perfil);
        }
        else{
            jSplitPane1.setRightComponent(panelHome);
        }
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jButtonGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGradeActionPerformed
        // TODO add your handling code here:
         if(jSplitPane1.getRightComponent() != grade){
            jSplitPane1.setRightComponent(grade);
        }
        else{
            jSplitPane1.setRightComponent(panelHome);
        }
    }//GEN-LAST:event_jButtonGradeActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        // TODO add your handling code here:
         if(jSplitPane1.getRightComponent() != agenda){
            jSplitPane1.setRightComponent(agenda);
        }
        else{
            jSplitPane1.setRightComponent(panelHome);
        }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    public javax.swing.JPanel getJPanelAmigos() {
        return jPanelAmigos;
    }
    
    public javax.swing.JPanel getJPanelSolicitacoes() {
        return jPanelSolicitacoes; 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGrade;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNotificacoes;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JList<String> jListAmigos;
    private javax.swing.JList<String> jListFeed;
    private javax.swing.JList<String> jListSolicitacoes;
    private javax.swing.JList<String> jListTurmas;
    private javax.swing.JPanel jPanelAmigos;
    private javax.swing.JPanel jPanelSolicitacoes;
    private javax.swing.JPanel jPanelTurmas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelColuna;
    private javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables
    private Aluno aluno; 
    private JFrameMain frameMain; 
    private JPanelPerfil perfil;
    private JPanelGrade grade;
    private JPanelAgenda agenda;

}