/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.util.ArrayList;
import java.util.Set;

/**
 *
 * @author lucas
 */
public class JPanelGrade extends javax.swing.JPanel {

    /**
     * Creates new form JPanelGrade
     */
    public JPanelGrade(Aluno aluno) {
        initComponents();
        this.aluno = aluno;
        
        if (jTable1.getColumnModel().getColumnCount() > 0) {
         jTable1.getColumnModel().getColumn(0).setResizable(false);
         jTable1.getColumnModel().getColumn(1).setResizable(false);
         jTable1.getColumnModel().getColumn(2).setResizable(false);
         jTable1.getColumnModel().getColumn(3).setResizable(false);
         jTable1.getColumnModel().getColumn(4).setResizable(false);
         jTable1.getColumnModel().getColumn(5).setResizable(false);
        
        criaRelacionadoTurma();
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(java.awt.Color.white);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("GRADE DE HORÁRIOS"));

        jTable1.setFont(new java.awt.Font("Yu Gothic", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", null, null, null, null, null},
                {"09:00", "", null, null, null, null},
                {"10:00", "", null, null, null, null},
                {"11:00", null, null, null, null, null},
                {"14:00", null, null, null, null, null},
                {"15:00", null, null, null, null, null},
                {"16:00", null, null, null, null, null},
                {"17:00", null, null, null, null, null},
                {"19:00", null, null, null, null, null},
                {"20:00", null, null, null, null, null},
                {"21:00", null, null, null, null, null},
                {"22:00", null, null, null, null, null}
            },
            new String [] {
                "", "Segunda", "Terça", "Quarta", "Quinta", "Sexta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void criaRelacionadoTurma() {
        if (aluno.getTurmas().size() != 0) {
            String[] listaTurmas = new String[aluno.getTurmas().size()]; 
            int aux = 0;
            for(Turma turma:aluno.getTurmas()) {
                System.out.println("entrei");

                listaTurmas[aux] = turma.getSigla(); 
                aux++; 
                Set<Integer> chaves = turma.getHorarios().keySet(); 
                for (Integer chave:chaves) {
                    ArrayList<Integer> horarios = turma.getHorarios().get(chave);
                    for(Integer inteiro:horarios) {
                        boolean stop = false; 
                        for(int i = 0; i < 12 && !stop; i++) {
                            String value = (String)jTable1.getValueAt(i, 0);  
                            if (value.contains(Integer.toString(inteiro))) {
                                stop = true;
                                jTable1.setValueAt(turma.getSigla(), i, chave);
                            }
                        }
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private Aluno aluno;
}
